apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Katachiyari/wordepress_k3s_argo-cd.git
    targetRevision: main
    path: wordpress
    helm:
      valueFiles:
        - values.prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
