apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 8Gi
  # EN: Bind to the existing NFS PV | FR: Lier au PV NFS existant
  volumeName: pv-nfs-content
